/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controler.ProjectController;
import Model.Project;
import javax.swing.JOptionPane;


/**
 *
 * @author Lucas Lima
 */
public class DialogScreenProject extends javax.swing.JDialog {

    ProjectController controller;
    
    
    
    public DialogScreenProject(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new ProjectController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolBarScreenDialog = new javax.swing.JPanel();
        ToolBarScreenDialogText = new javax.swing.JLabel();
        ToolBarScreenDialogIcon = new javax.swing.JLabel();
        SpaceProject = new javax.swing.JPanel();
        SpaceProjectTittleName = new javax.swing.JLabel();
        SpaceProjectInputName = new javax.swing.JTextField();
        SpaceProjectTittleDescription = new javax.swing.JLabel();
        ScroolPainel = new javax.swing.JScrollPane();
        SpaceProjectInputText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));

        ToolBarScreenDialog.setBackground(new java.awt.Color(13, 15, 27));

        ToolBarScreenDialogText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ToolBarScreenDialogText.setForeground(new java.awt.Color(209, 140, 48));
        ToolBarScreenDialogText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToolBarScreenDialogText.setText("Projeto");

        ToolBarScreenDialogIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToolBarScreenDialogIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas Lima\\Desktop\\Project\\app\\src\\resources\\Icons\\tickcheck.png")); // NOI18N
        ToolBarScreenDialogIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToolBarScreenDialogIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ToolBarScreenDialogLayout = new javax.swing.GroupLayout(ToolBarScreenDialog);
        ToolBarScreenDialog.setLayout(ToolBarScreenDialogLayout);
        ToolBarScreenDialogLayout.setHorizontalGroup(
            ToolBarScreenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarScreenDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarScreenDialogText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToolBarScreenDialogIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ToolBarScreenDialogLayout.setVerticalGroup(
            ToolBarScreenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolBarScreenDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolBarScreenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ToolBarScreenDialogLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(ToolBarScreenDialogIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ToolBarScreenDialogText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SpaceProject.setBackground(new java.awt.Color(23, 28, 51));

        SpaceProjectTittleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpaceProjectTittleName.setForeground(new java.awt.Color(205, 83, 39));
        SpaceProjectTittleName.setText("Nome");

        SpaceProjectInputName.setBackground(new java.awt.Color(37, 43, 63));
        SpaceProjectInputName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpaceProjectInputName.setForeground(new java.awt.Color(205, 83, 39));
        SpaceProjectInputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaceProjectInputNameActionPerformed(evt);
            }
        });

        SpaceProjectTittleDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpaceProjectTittleDescription.setForeground(new java.awt.Color(205, 83, 39));
        SpaceProjectTittleDescription.setText("Descrição");

        SpaceProjectInputText.setBackground(new java.awt.Color(37, 43, 63));
        SpaceProjectInputText.setColumns(20);
        SpaceProjectInputText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpaceProjectInputText.setForeground(new java.awt.Color(205, 83, 39));
        SpaceProjectInputText.setRows(5);
        ScroolPainel.setViewportView(SpaceProjectInputText);

        javax.swing.GroupLayout SpaceProjectLayout = new javax.swing.GroupLayout(SpaceProject);
        SpaceProject.setLayout(SpaceProjectLayout);
        SpaceProjectLayout.setHorizontalGroup(
            SpaceProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpaceProjectLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(SpaceProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpaceProjectTittleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpaceProjectInputName)
                    .addComponent(SpaceProjectTittleDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScroolPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        SpaceProjectLayout.setVerticalGroup(
            SpaceProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpaceProjectLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SpaceProjectTittleName)
                .addGap(14, 14, 14)
                .addComponent(SpaceProjectInputName)
                .addGap(14, 14, 14)
                .addComponent(SpaceProjectTittleDescription)
                .addGap(14, 14, 14)
                .addComponent(ScroolPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBarScreenDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SpaceProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBarScreenDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SpaceProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToolBarScreenDialogIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolBarScreenDialogIconMouseClicked
        // TODO add your handling code here:
        
        try {
            //Verifica se a entrada do input é igual a 0.
            if(!SpaceProjectInputName.getText().equals("")){
                //Cria um projeto.
                Project project = new Project();
                //Pega o texto dentro do componente de input.
                project.setName(SpaceProjectInputName.getText());
                project.setDescription(SpaceProjectInputText.getText());
                //Chama a função de salvar do controlador.
                controller.save(project);
                //Expõe uma mensagem de confirmação da ação para o usuário.
                JOptionPane.showMessageDialog(rootPane,"Projeto salvo com sucesso.");
                 //Fecha a janela de diálogo.
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Projeto não foi salvo, "
                        + "Pois o campo nome não foi preenchido.");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
    }//GEN-LAST:event_ToolBarScreenDialogIconMouseClicked

    private void SpaceProjectInputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaceProjectInputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpaceProjectInputNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //Definição de template.
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogScreenProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogScreenProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogScreenProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogScreenProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogScreenProject dialog = new DialogScreenProject(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScroolPainel;
    private javax.swing.JPanel SpaceProject;
    private javax.swing.JTextField SpaceProjectInputName;
    private javax.swing.JTextArea SpaceProjectInputText;
    private javax.swing.JLabel SpaceProjectTittleDescription;
    private javax.swing.JLabel SpaceProjectTittleName;
    private javax.swing.JPanel ToolBarScreenDialog;
    private javax.swing.JLabel ToolBarScreenDialogIcon;
    private javax.swing.JLabel ToolBarScreenDialogText;
    // End of variables declaration//GEN-END:variables
}
