/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controler.TaskController;
import Model.Project;
import Model.Task;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Lima
 */
public class DialogScreenTask extends javax.swing.JDialog {

    TaskController controller;
    Project project;
    
    public DialogScreenTask(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        hideErrorFields();
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        TittlePane = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Tittle = new javax.swing.JLabel();
        BodyPane = new javax.swing.JPanel();
        BodyTextName = new javax.swing.JLabel();
        BodyTextNameInput = new javax.swing.JTextField();
        BodyTextDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BodyTextDescriptionInput = new javax.swing.JTextArea();
        BodyTextDeadline = new javax.swing.JLabel();
        BodyTextNotes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BodyTextNotesInput = new javax.swing.JTextArea();
        BodyTextDeadlineInput = new javax.swing.JFormattedTextField();
        ObrigatoryNameInput = new javax.swing.JLabel();
        ObrigatoryDeadlineInput = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        TittlePane.setBackground(new java.awt.Color(13, 15, 27));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas Lima\\Desktop\\Project\\app\\src\\resources\\Icons\\tickcheck.png")); // NOI18N
        Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconMouseClicked(evt);
            }
        });

        Tittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Tittle.setForeground(new java.awt.Color(209, 140, 48));
        Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle.setText("Tarefa");

        javax.swing.GroupLayout TittlePaneLayout = new javax.swing.GroupLayout(TittlePane);
        TittlePane.setLayout(TittlePaneLayout);
        TittlePaneLayout.setHorizontalGroup(
            TittlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittlePaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        TittlePaneLayout.setVerticalGroup(
            TittlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittlePaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(TittlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        BodyPane.setBackground(new java.awt.Color(23, 28, 51));

        BodyTextName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BodyTextName.setForeground(new java.awt.Color(205, 83, 39));
        BodyTextName.setText("Nome");

        BodyTextNameInput.setBackground(new java.awt.Color(37, 43, 63));
        BodyTextNameInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BodyTextNameInput.setForeground(new java.awt.Color(205, 83, 39));

        BodyTextDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BodyTextDescription.setForeground(new java.awt.Color(205, 83, 39));
        BodyTextDescription.setText("Descrição");

        BodyTextDescriptionInput.setBackground(new java.awt.Color(37, 43, 63));
        BodyTextDescriptionInput.setColumns(20);
        BodyTextDescriptionInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BodyTextDescriptionInput.setForeground(new java.awt.Color(205, 83, 39));
        BodyTextDescriptionInput.setRows(5);
        jScrollPane1.setViewportView(BodyTextDescriptionInput);

        BodyTextDeadline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BodyTextDeadline.setForeground(new java.awt.Color(205, 83, 39));
        BodyTextDeadline.setText("Prazo");

        BodyTextNotes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BodyTextNotes.setForeground(new java.awt.Color(205, 83, 39));
        BodyTextNotes.setText("Notas");

        BodyTextNotesInput.setBackground(new java.awt.Color(37, 43, 63));
        BodyTextNotesInput.setColumns(20);
        BodyTextNotesInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BodyTextNotesInput.setForeground(new java.awt.Color(205, 83, 39));
        BodyTextNotesInput.setRows(5);
        jScrollPane3.setViewportView(BodyTextNotesInput);

        BodyTextDeadlineInput.setBackground(new java.awt.Color(37, 43, 63));
        BodyTextDeadlineInput.setForeground(new java.awt.Color(205, 83, 39));
        BodyTextDeadlineInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        BodyTextDeadlineInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ObrigatoryNameInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ObrigatoryNameInput.setForeground(new java.awt.Color(205, 83, 39));
        ObrigatoryNameInput.setText("Campo de nome obrigatório");

        ObrigatoryDeadlineInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ObrigatoryDeadlineInput.setForeground(new java.awt.Color(205, 83, 39));
        ObrigatoryDeadlineInput.setText("Campo de prazo obrigatório");

        javax.swing.GroupLayout BodyPaneLayout = new javax.swing.GroupLayout(BodyPane);
        BodyPane.setLayout(BodyPaneLayout);
        BodyPaneLayout.setHorizontalGroup(
            BodyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BodyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BodyTextDeadlineInput)
                    .addComponent(BodyTextName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BodyTextNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BodyPaneLayout.createSequentialGroup()
                        .addComponent(BodyTextDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(BodyTextDeadline, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BodyTextNotes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(14, 14, 14))
            .addGroup(BodyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ObrigatoryNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BodyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ObrigatoryDeadlineInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BodyPaneLayout.setVerticalGroup(
            BodyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BodyTextName)
                .addGap(12, 12, 12)
                .addComponent(BodyTextNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ObrigatoryNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BodyTextDescription)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(BodyTextDeadline)
                .addGap(12, 12, 12)
                .addComponent(BodyTextDeadlineInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ObrigatoryDeadlineInput)
                .addGap(12, 12, 12)
                .addComponent(BodyTextNotes)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TittlePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BodyPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TittlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BodyPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMouseClicked
        try{
          if(isFieldsValid()){
                Task task = new Task();
                //O id é setado na screen principal.
                task.setIdProject(project.getId());
                task.setName(BodyTextNameInput.getText());
                task.setDescription(BodyTextDescriptionInput.getText());
                task.setNotes(BodyTextNotesInput.getText());
                task.setIsCompleted(false);
                //Formata o formato da data.
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/y");
                Date deadline = null;

                deadline = dateFormat.parse(BodyTextDeadlineInput.getText());
                task.setDeadline(deadline);
                controller.save(task);
                JOptionPane.showMessageDialog(rootPane,"Tarefa salva com sucesso.");
                this.dispose();
          }else{
                hideErrorFields();
                if(BodyTextNameInput.getText().isEmpty()){
                    ObrigatoryNameInput.setVisible(true);
                }
                if(BodyTextDeadlineInput.getText().isEmpty()){
                    ObrigatoryDeadlineInput.setVisible(true);
                }
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_IconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogScreenTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogScreenTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogScreenTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogScreenTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogScreenTask dialog = new DialogScreenTask(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPane;
    private javax.swing.JLabel BodyTextDeadline;
    private javax.swing.JFormattedTextField BodyTextDeadlineInput;
    private javax.swing.JLabel BodyTextDescription;
    private javax.swing.JTextArea BodyTextDescriptionInput;
    private javax.swing.JLabel BodyTextName;
    private javax.swing.JTextField BodyTextNameInput;
    private javax.swing.JLabel BodyTextNotes;
    private javax.swing.JTextArea BodyTextNotesInput;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel ObrigatoryDeadlineInput;
    private javax.swing.JLabel ObrigatoryNameInput;
    private javax.swing.JLabel Tittle;
    private javax.swing.JPanel TittlePane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }
    
    public void hideErrorFields(){
        ObrigatoryNameInput.setVisible(false);
        ObrigatoryDeadlineInput.setVisible(false);
    }
    
    public boolean isFieldsValid(){
        if((!BodyTextNameInput.getText().isEmpty()) && (!BodyTextDeadlineInput.getText().isEmpty())){
            return true;
        }else{
            return false;
        }
    }
}
