/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template.
 */
package View;

import Controler.ProjectController;
import Controler.TaskController;
import Model.Project;
import Model.Task;
import Util.ButtonColumnCelllRender;
import Util.DeadlineColumnCellRender;
import Util.TaskTableModel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
/**
 *
 * @author Lucas Lima
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;
    
    DefaultListModel projectsModel;
    TaskTableModel tasksModel;
    
    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        //Deve ter uma ordem de execução.
        initComponents();
        
        initDataController();
        initComponentModel();
        
        decorateTableTasks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPaneTask = new javax.swing.JScrollPane();
        SpaceTaskTable = new javax.swing.JTable();
        ToolBar = new javax.swing.JPanel();
        ToolBarTittle = new javax.swing.JLabel();
        ToolBarText = new javax.swing.JLabel();
        ToolBarLogo = new javax.swing.JLabel();
        MainBar = new javax.swing.JPanel();
        ProjectTittleAdd = new javax.swing.JPanel();
        ProjectTittleAddText = new javax.swing.JLabel();
        ProjectTittleAddIcon = new javax.swing.JLabel();
        TaskTittleAdd = new javax.swing.JPanel();
        TaskTittleAddText = new javax.swing.JLabel();
        TaskTittleAddIcon = new javax.swing.JLabel();
        SpaceList = new javax.swing.JPanel();
        AllList = new javax.swing.JScrollPane();
        ListProject = new javax.swing.JList<>();
        SpaceTask = new javax.swing.JPanel();
        SpaceTaskInside = new javax.swing.JPanel();
        SpaceTaskInsideIcon = new javax.swing.JLabel();
        SpaceTaskInsideTextOne = new javax.swing.JLabel();
        SpaceTaskInsideTextTwo = new javax.swing.JLabel();

        SpaceTaskTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpaceTaskTable.setForeground(new java.awt.Color(205, 83, 39));
        SpaceTaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SpaceTaskTable.setGridColor(new java.awt.Color(255, 255, 255));
        SpaceTaskTable.setRowHeight(50);
        SpaceTaskTable.setSelectionBackground(new java.awt.Color(209, 140, 48));
        SpaceTaskTable.setSelectionForeground(new java.awt.Color(205, 83, 39));
        SpaceTaskTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SpaceTaskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpaceTaskTableMouseClicked(evt);
            }
        });
        ScrollPaneTask.setViewportView(SpaceTaskTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 600));

        ToolBar.setBackground(new java.awt.Color(13, 15, 27));

        ToolBarTittle.setBackground(new java.awt.Color(255, 255, 255));
        ToolBarTittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ToolBarTittle.setForeground(new java.awt.Color(209, 140, 48));
        ToolBarTittle.setText("Alpha Studio Project App");

        ToolBarText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ToolBarText.setForeground(new java.awt.Color(205, 83, 39));
        ToolBarText.setText("Sua ferramenta Alpha de projetos.");

        ToolBarLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToolBarLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas Lima\\Desktop\\Project\\app\\src\\resources\\Icons\\Sem título-2LOGO97.png")); // NOI18N

        javax.swing.GroupLayout ToolBarLayout = new javax.swing.GroupLayout(ToolBar);
        ToolBar.setLayout(ToolBarLayout);
        ToolBarLayout.setHorizontalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToolBarTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ToolBarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ToolBarText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToolBarLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ToolBarLayout.setVerticalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarLayout.createSequentialGroup()
                .addGroup(ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ToolBarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ToolBarTittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToolBarText))
                    .addGroup(ToolBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ToolBarLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainBar.setBackground(new java.awt.Color(23, 28, 51));

        ProjectTittleAdd.setBackground(new java.awt.Color(255, 255, 255));
        ProjectTittleAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProjectTittleAddText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProjectTittleAddText.setForeground(new java.awt.Color(205, 83, 39));
        ProjectTittleAddText.setText("Projetos");

        ProjectTittleAddIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas Lima\\Desktop\\Project\\app\\src\\resources\\Icons\\Sem título-2adicao.png")); // NOI18N
        ProjectTittleAddIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectTittleAddIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProjectTittleAddLayout = new javax.swing.GroupLayout(ProjectTittleAdd);
        ProjectTittleAdd.setLayout(ProjectTittleAddLayout);
        ProjectTittleAddLayout.setHorizontalGroup(
            ProjectTittleAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectTittleAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectTittleAddText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProjectTittleAddIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProjectTittleAddLayout.setVerticalGroup(
            ProjectTittleAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectTittleAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectTittleAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectTittleAddLayout.createSequentialGroup()
                        .addComponent(ProjectTittleAddIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ProjectTittleAddText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TaskTittleAdd.setBackground(new java.awt.Color(255, 255, 255));
        TaskTittleAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TaskTittleAddText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TaskTittleAddText.setForeground(new java.awt.Color(205, 83, 39));
        TaskTittleAddText.setText("Tarefas");

        TaskTittleAddIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas Lima\\Desktop\\Project\\app\\src\\resources\\Icons\\Sem título-2adicao.png")); // NOI18N
        TaskTittleAddIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskTittleAddIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TaskTittleAddLayout = new javax.swing.GroupLayout(TaskTittleAdd);
        TaskTittleAdd.setLayout(TaskTittleAddLayout);
        TaskTittleAddLayout.setHorizontalGroup(
            TaskTittleAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskTittleAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskTittleAddText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TaskTittleAddIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TaskTittleAddLayout.setVerticalGroup(
            TaskTittleAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskTittleAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskTittleAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TaskTittleAddLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TaskTittleAddIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TaskTittleAddText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SpaceList.setBackground(new java.awt.Color(18, 30, 49));
        SpaceList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListProject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ListProject.setForeground(new java.awt.Color(205, 83, 39));
        ListProject.setFixedCellHeight(50);
        ListProject.setSelectionBackground(new java.awt.Color(209, 140, 48));
        ListProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListProjectMouseClicked(evt);
            }
        });
        AllList.setViewportView(ListProject);

        javax.swing.GroupLayout SpaceListLayout = new javax.swing.GroupLayout(SpaceList);
        SpaceList.setLayout(SpaceListLayout);
        SpaceListLayout.setHorizontalGroup(
            SpaceListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        SpaceListLayout.setVerticalGroup(
            SpaceListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllList)
        );

        SpaceTask.setBackground(new java.awt.Color(18, 30, 49));
        SpaceTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SpaceTask.setLayout(new java.awt.BorderLayout());

        SpaceTaskInside.setBackground(new java.awt.Color(18, 30, 49));

        SpaceTaskInsideIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SpaceTaskInsideIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas Lima\\Desktop\\Project\\app\\src\\resources\\Icons\\listsfichario.png")); // NOI18N

        SpaceTaskInsideTextOne.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpaceTaskInsideTextOne.setForeground(new java.awt.Color(205, 83, 39));
        SpaceTaskInsideTextOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SpaceTaskInsideTextOne.setText("Nenhuma tarefa disponível");

        SpaceTaskInsideTextTwo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpaceTaskInsideTextTwo.setForeground(new java.awt.Color(209, 140, 48));
        SpaceTaskInsideTextTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SpaceTaskInsideTextTwo.setText("Clique no \"+\" para adicionar tarefa.");

        javax.swing.GroupLayout SpaceTaskInsideLayout = new javax.swing.GroupLayout(SpaceTaskInside);
        SpaceTaskInside.setLayout(SpaceTaskInsideLayout);
        SpaceTaskInsideLayout.setHorizontalGroup(
            SpaceTaskInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpaceTaskInsideLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(SpaceTaskInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpaceTaskInsideIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpaceTaskInsideTextOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpaceTaskInsideTextTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SpaceTaskInsideLayout.setVerticalGroup(
            SpaceTaskInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpaceTaskInsideLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(SpaceTaskInsideIcon)
                .addGap(18, 18, 18)
                .addComponent(SpaceTaskInsideTextOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpaceTaskInsideTextTwo)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        SpaceTask.add(SpaceTaskInside, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout MainBarLayout = new javax.swing.GroupLayout(MainBar);
        MainBar.setLayout(MainBarLayout);
        MainBarLayout.setHorizontalGroup(
            MainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(MainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SpaceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProjectTittleAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(MainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpaceTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaskTittleAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        MainBarLayout.setVerticalGroup(
            MainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(MainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectTittleAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaskTittleAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpaceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpaceTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectTittleAddIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectTittleAddIconMouseClicked
        // TODO add your handling code here:
        DialogScreenProject dialogScreenProject = new DialogScreenProject(this, rootPaneCheckingEnabled);
        dialogScreenProject.setVisible(true);
        
        //Adiciona um ouvinte(Gerador de evento), toda vez que a janela fechar, gera evento.
        //o evendo dispara uma função que chama a função loadProjects().
        dialogScreenProject.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e){
                loadProjects();
            }
        });
    }//GEN-LAST:event_ProjectTittleAddIconMouseClicked

    private void TaskTittleAddIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskTittleAddIconMouseClicked
        DialogScreenTask taskDialogScreen = new DialogScreenTask(this, rootPaneCheckingEnabled);
        //taskDialogScreen.setProject(null);
        //Pega o ídice do item selecionado.
        int projectIndex = ListProject.getSelectedIndex();
        //O (project) Faz um parse para o formato inteiro.
        Project project = (Project)projectsModel.get(projectIndex);
        taskDialogScreen.setProject(project);
        taskDialogScreen.setVisible(true);
        //Adiciona um objeto ouvinte à taskDialogScreen.
        taskDialogScreen.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e){
                int projectIndex = ListProject.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
            }
        });
    }//GEN-LAST:event_TaskTittleAddIconMouseClicked

    private void SpaceTaskTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpaceTaskTableMouseClicked
        // TODO add your handling code here:
        //Peg uma linha a partir de um ponto da tela
        int rowIndex = SpaceTaskTable.rowAtPoint(evt.getPoint());
        int columnIndex = SpaceTaskTable.columnAtPoint(evt.getPoint());
        Task task = tasksModel.getTasks().get(rowIndex);
        
        switch(columnIndex){
            case 3: 
               taskController.update(task);
               break;
            case 4: 
                break;
            case 5: 
                taskController.removeById(task.getId());
                tasksModel.getTasks().remove(task);
                int projectIndex = ListProject.getSelectedIndex();
                Project project =(Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
                break;
            
        }
    }//GEN-LAST:event_SpaceTaskTableMouseClicked

    private void showTableTasks(boolean hasTasks){
        //Verifica se as tarefas foram carregadas.
        if(hasTasks){
            //Verifica se a mensagem de lista vazia está visível para o usuário.
            if(SpaceTaskInside.isVisible()){
                //Esconde a visibilidade.
                SpaceTaskInside.setVisible(false);
                //Remove o componente da tela.
                SpaceTask.remove(SpaceTaskInside);
            }
            //Adiciona o scroll ao painel.
            SpaceTask.add(ScrollPaneTask);
            //Deixa o elemento visível dentro do painel.
            ScrollPaneTask.setVisible(true);
            //Pega o tamanho do painel e envia os dados para o scrollPaneTask.
            ScrollPaneTask.setSize(SpaceTask.getWidth(), SpaceTask.getHeight());
        }else{
            if(ScrollPaneTask.isVisible()){
                ScrollPaneTask.setVisible(false);
                SpaceTask.remove(ScrollPaneTask);
            }
            
            SpaceTask.add(SpaceTaskInside);
            SpaceTaskInside.setVisible(true);
            SpaceTaskInside.setSize(SpaceTask.getWidth(),SpaceTask.getHeight());
        }
    }
    
    private void ListProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListProjectMouseClicked
        // TODO add your handling code here:
        //Retorna o índice do item clicado.
        int projectIndex = ListProject.getSelectedIndex();
        //Converte os dados.
        Project project = (Project)projectsModel.get(projectIndex);
        loadTasks(project.getId());
    }//GEN-LAST:event_ListProjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //Java swing é o template utilizado.
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AllList;
    private javax.swing.JList<String> ListProject;
    private javax.swing.JPanel MainBar;
    private javax.swing.JPanel ProjectTittleAdd;
    private javax.swing.JLabel ProjectTittleAddIcon;
    private javax.swing.JLabel ProjectTittleAddText;
    private javax.swing.JScrollPane ScrollPaneTask;
    private javax.swing.JPanel SpaceList;
    private javax.swing.JPanel SpaceTask;
    private javax.swing.JPanel SpaceTaskInside;
    private javax.swing.JLabel SpaceTaskInsideIcon;
    private javax.swing.JLabel SpaceTaskInsideTextOne;
    private javax.swing.JLabel SpaceTaskInsideTextTwo;
    private javax.swing.JTable SpaceTaskTable;
    private javax.swing.JPanel TaskTittleAdd;
    private javax.swing.JLabel TaskTittleAddIcon;
    private javax.swing.JLabel TaskTittleAddText;
    private javax.swing.JPanel ToolBar;
    private javax.swing.JLabel ToolBarLogo;
    private javax.swing.JLabel ToolBarText;
    private javax.swing.JLabel ToolBarTittle;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTasks(){
        //Seta configurações de decoração para tabela dentro das task.
        SpaceTaskTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        SpaceTaskTable.getTableHeader().setBackground(new Color(37, 43, 63));
        SpaceTaskTable.getTableHeader().setForeground(new Color(209, 140, 48));
        
        
        //Seta a forma de renderizar implementada pelo método definido.
        SpaceTaskTable.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRender());
        SpaceTaskTable.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCelllRender("edit"));
         SpaceTaskTable.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCelllRender("delete"));
        
        //Permite criação automática de um sort por coluna, ou seja, ordenação das linhas.
        SpaceTaskTable.setAutoCreateRowSorter(true);
    }

    public void initDataController(){
        projectController = new ProjectController();
        taskController = new TaskController();
        
    }
    
    public void initComponentModel(){
        projectsModel = new DefaultListModel();
        loadProjects();
        
        
        tasksModel = new TaskTableModel();
        //Seta o modelo de acordo com o objeto determinado no Util, e seus dados.
        SpaceTaskTable.setModel(tasksModel);
        
        ///Verifica se fi setado algum projeto.
        if(!projectsModel.isEmpty()){
            //Seta o primeiro projeto.
            ListProject.setSelectedIndex(0);
            int projectIndex = ListProject.getSelectedIndex();
            Project project = (Project) projectsModel.get(projectIndex);
            loadTasks(project.getId());
        }
    }
    
    public void loadTasks(int idProject){
        //Carrega todas propriedades de um projeto determinado.
        List<Task> tasks = taskController.getAll(idProject);
        tasksModel.setTasks(tasks); 
        
        //verifica se está vazia a tabela.
        showTableTasks(!tasks.isEmpty());
    }
    
    public void loadProjects(){
        List<Project> projects = projectController.getAll();
        //Remove os dados caso já tenha.
        projectsModel.clear();
        
        for (int i = 0; i < projects.size(); i++) {
            projectsModel.addElement(projects.get(i));
        }
        ListProject.setModel(projectsModel);
    }
}
